project:
  type: website
  output-dir: docs

website:
  title: "EnquÃªtes quantitatives"
  site-url: "https://tblk.github.io/enquetes-quantitatives/"
  open-graph: true
  favicon: advent_04_211.png
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - programme.qmd
      - faq.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

lang: fr

